// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avphywyhlxajyhqudkts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2cGh5d3lobHhhanlocXVka3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4OTM1MDEsImV4cCI6MjA1MDQ2OTUwMX0.wwNFD49QaoTOc36E37MRpBtwptSYi5zrKmUSqPSLt04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);